apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
data:
  smb.conf: |
    # Global parameters
    [global]
            dns proxy = No
            map to guest = Bad User
            name resolve order = bcast host
            netbios name = media
            security = USER
            server string = Server
            idmap config * : backend = tdb

    [Photos]
            create mask = 0777
            guest ok = Yes
            path = /srv/photos
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [TV]
            create mask = 0777
            guest ok = Yes
            path = /srv/tv
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [Movies]
            create mask = 0777
            guest ok = Yes
            path = /srv/movies
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [Games]
            create mask = 0777
            guest ok = Yes
            path = /srv/games
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [Downloads]
            create mask = 0777
            guest ok = Yes
            path = /srv/downloads
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [Videos]
            create mask = 0777
            guest ok = Yes
            path = /srv/videos
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [Bryce]
            create mask = 0777
            guest ok = Yes
            path = /srv/bryce
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

    [Anacleto]
            create mask = 0777
            guest ok = Yes
            path = /srv/anacleto
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777
kind: ConfigMap
metadata:
  name: samba-config
  namespace: media
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: smb-server
  name: smb-server-tcp
  namespace: media
spec:
  loadBalancerIP: 172.16.10.2
  ports:
  - name: port-8384
    port: 443
    protocol: TCP
    targetPort: 8384
  - name: port-22000
    port: 22000
    protocol: TCP
    targetPort: 22000
  - name: port-139
    port: 139
    protocol: TCP
    targetPort: 139
  - name: port-445
    port: 445
    protocol: TCP
    targetPort: 445
  - name: port-32400
    port: 32400
    protocol: TCP
    targetPort: 32400
  - name: port-3005
    port: 3005
    protocol: TCP
    targetPort: 3005
  - name: port-8324
    port: 8324
    protocol: TCP
    targetPort: 8324
  - name: port-32469
    port: 32469
    protocol: TCP
    targetPort: 32469
  selector:
    app: smb-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: smb-server
  name: smb-server-udp
  namespace: media
spec:
  loadBalancerIP: 172.16.10.2
  ports:
  - name: port-21027
    port: 21027
    protocol: UDP
    targetPort: 21027
  - name: port-137
    port: 137
    protocol: UDP
    targetPort: 137
  - name: port-138
    port: 138
    protocol: UDP
    targetPort: 138
  - name: port-1900
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: port-32410
    port: 32410
    protocol: UDP
    targetPort: 32410
  - name: port-32412
    port: 32412
    protocol: UDP
    targetPort: 32412
  - name: port-32413
    port: 32413
    protocol: UDP
    targetPort: 32413
  - name: port-32414
    port: 32414
    protocol: UDP
    targetPort: 32414
  selector:
    app: smb-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smb-server
  name: smb-server
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smb-server
        configmap-version: "17"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: smb-server
            namespaces:
            - jcr
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: PLEX_PGID
          value: "1000"
        - name: PLEX_PUID
          value: "1000"
        - name: TZ
          value: Canada/Pacific
        - name: UMASK_SET
          value: "022"
        - name: PLEX_CLAIM
          value: "022"
        - name: ADVERTISE_IP
          value: http://172.16.10.2:32400/
      - image: plexinc/pms-docker
        imagePullPolicy: Always
        name: plex
        resources:
          limits:
            cpu: "2"
            memory: 2000Mi
          requests:
            cpu: ".5"
            memory: 500Mi
        volumeMounts:
        - mountPath: /srv/bryce
          name: bryce
        - mountPath: /srv/anacleto
          name: anacleto
        - mountPath: /srv/photos
          name: photos
        - mountPath: /srv/tv
          name: tv
        - mountPath: /srv/movies
          name: movies
        - mountPath: /srv/games
          name: games
        - mountPath: /srv/downloads
          name: downloads
        - mountPath: /srv/videos
          name: videos
        - mountPath: /transcode
          name: plex-transcode
        - mountPath: /config
          name: plex-config
      - image: linuxserver/syncthing
        imagePullPolicy: Always
        name: syncthing
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: ".5"
            memory: 500Mi
        volumeMounts:
        - mountPath: /config
          name: syncthing-config
        - mountPath: /data/photos
          name: photos
        - mountPath: /data/anacleto
          name: anacleto
        - mountPath: /data/bryce
          name: bryce
      - image: brycemclachlan/smb-server:latest
        imagePullPolicy: Always
        name: smb-server
        resources:
          limits:
            cpu: "2"
            memory: 1000Mi
          requests:
            cpu: ".1"
            memory: 100Mi
        volumeMounts:
        - mountPath: /srv/bryce
          name: bryce
        - mountPath: /srv/anacleto
          name: anacleto
        - mountPath: /srv/photos
          name: photos
        - mountPath: /srv/tv
          name: tv
        - mountPath: /srv/movies
          name: movies
        - mountPath: /srv/games
          name: games
        - mountPath: /srv/downloads
          name: downloads
        - mountPath: /srv/videos
          name: videos
        - mountPath: /etc/samba/
          name: samba-config
      restartPolicy: Always
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos
      - name: tv
        persistentVolumeClaim:
          claimName: tv
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: games
        persistentVolumeClaim:
          claimName: games
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: videos
        persistentVolumeClaim:
          claimName: videos
      - name: anacleto
        persistentVolumeClaim:
          claimName: anacleto
      - name: bryce
        persistentVolumeClaim:
          claimName: bryce
      - configMap:
          name: samba-config
        name: samba-config
      - name: syncthing-config
        persistentVolumeClaim:
          claimName: syncthing-config
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - emptyDir: {}
        name: plex-transcode
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: smb-server
  namespace: media
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: smb-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anacleto
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bryce
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
